org: guillaumeboussus
service: m200-backend
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  iam:
    role: arn:aws:iam::156529843879:role/LabRole

  environment:
    STAGE: ${self:provider.stage}
    ORDERS_TABLE: ${self:service}-orders-${self:provider.stage}
    CONNECTIONS_TABLE: ${self:service}-connections-${self:provider.stage}
    EVENT_BUS_NAME: m200bus-${self:provider.stage}

    WEBSOCKET_ENDPOINT:
      Fn::Join:
        - ''
        - - 'https://'
          - !Ref WebsocketsApi
          - '.execute-api.'
          - ${self:provider.region}
          - '.amazonaws.com/'
          - ${self:provider.stage}

functions:

  createOrder:
    handler: src/functions/order/create.handler
    events:
      - http:
          path: orders
          method: post
          cors: true

  updateOrderStatus:
    handler: src/functions/order/updateStatus.handler
    events:
      - http:
          path: orders/{orderId}/status
          method: put
          cors: true

  getOrder:
    handler: src/functions/order/get.handler
    events:
      - http:
          path: orders/{orderId}
          method: get
          cors: true

  listOrders:
    handler: src/functions/order/list.handler
    events:
      - http:
          path: orders
          method: get
          cors: true

  workflowUpdate:
    handler: src/functions/workflow/update.handler
    events:
      - eventBridge:
          eventBus: ${self:provider.environment.EVENT_BUS_NAME}
          pattern:
            source:
              - order.service
            detail-type:
              - Order Created

  websocketConnect:
    handler: src/functions/websocket/connect.handler
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: src/functions/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  websocketBroadcast:
    handler: src/functions/websocket/broadcast.handler
    events:
      - eventBridge:
          eventBus: ${self:provider.environment.EVENT_BUS_NAME}
          pattern:
            source:
              - order.service
            detail-type:
              - Order Created

resources:
  Resources:

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ORDERS_TABLE}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CONNECTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
